---
- name: Restart Reloader Deployment
  ansible.builtin.include_role:
    name: dev_infra.deployment.k8s_deployment
    tasks_from: rollout_restart
  vars:
    dev_infra_deployment_restart_kind: Deployment
    dev_infra_deployment_restart_namespace: "{{ dev_infra_deployment_reloader_namespace }}"
    dev_infra_deployment_restart_name: "{{ dev_infra_deployment_reloader_deployment_name }}"

- name: Wait for Reloader rollout after restart
  ansible.builtin.include_role:
    name: dev_infra.deployment.k8s_deployment
    tasks_from: rollout_status
  vars:
    dev_infra_deployment_rollout_namespace: "{{ dev_infra_deployment_reloader_namespace }}"
    dev_infra_deployment_rollout_resource: "deployment/{{ dev_infra_deployment_reloader_deployment_name }}"
    dev_infra_deployment_rollout_timeout: "{{ dev_infra_deployment_reloader_timeout }}"
    dev_infra_deployment_rollout_timeout_seconds: "{{ dev_infra_deployment_reloader_timeout_seconds }}"
