---
- name: Uninstall Reloader Helm release
  ansible.builtin.include_role:
    name: dev_infra.deployment.k8s_deployment
    tasks_from: helm_uninstall
  vars:
    dev_infra_deployment_helm_release_name: "{{ dev_infra_deployment_reloader_release_name }}"
    dev_infra_deployment_helm_namespace: "{{ dev_infra_deployment_reloader_namespace }}"

- name: Delete Reloader Pods before namespace deletion
  ansible.builtin.include_role:
    name: dev_infra.deployment.k8s_deployment
    tasks_from: delete_labelled
  vars:
    dev_infra_deployment_delete_kind: Pod
    dev_infra_deployment_delete_namespace: "{{ dev_infra_deployment_reloader_namespace }}"
    dev_infra_deployment_delete_label_selectors:
      - "{{ dev_infra_deployment_reloader_pod_selector }}"
    dev_infra_deployment_delete_options:
      gracePeriodSeconds: 0
    dev_infra_deployment_delete_wait_sleep: "{{ dev_infra_deployment_pod_wait_sleep_seconds }}"

- name: Delete Reloader namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ dev_infra_deployment_kubeconfig }}"
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ dev_infra_deployment_reloader_namespace }}"
    wait: true
    wait_timeout: "{{ dev_infra_deployment_long_wait_timeout_seconds }}"
  vars:
    ansible_python_interpreter: "{{ dev_infra_deployment_python_interpreter }}"
