---
- name: Stage LDAP artifacts
  ansible.builtin.import_tasks: stage.yml

- name: Delete LDAP manifest
  ansible.builtin.include_role:
    name: dev_infra.deployment.k8s_deployment
    tasks_from: delete_manifest
  vars:
    dev_infra_deployment_delete_path: "{{ dev_infra_deployment_ldap_manifest }}"

- name: Delete LDAP user upsert Job
  kubernetes.core.k8s:
    kubeconfig: "{{ dev_infra_deployment_kubeconfig }}"
    state: absent
    api_version: batch/v1
    kind: Job
    namespace: "{{ dev_infra_deployment_namespace }}"
    name: "{{ dev_infra_deployment_ldap_user_upsert_job_name }}"
    wait: true
    wait_timeout: "{{ dev_infra_deployment_wait_timeout_seconds }}"
  vars:
    ansible_python_interpreter: "{{ dev_infra_deployment_python_interpreter }}"
  when: not ansible_check_mode

- name: Delete LDAP user upsert Secret
  kubernetes.core.k8s:
    kubeconfig: "{{ dev_infra_deployment_kubeconfig }}"
    state: absent
    api_version: v1
    kind: Secret
    namespace: "{{ dev_infra_deployment_namespace }}"
    name: "{{ dev_infra_deployment_ldap_user_upsert_secret_name }}"
    wait: true
    wait_timeout: "{{ dev_infra_deployment_wait_timeout_seconds }}"
  vars:
    ansible_python_interpreter: "{{ dev_infra_deployment_python_interpreter }}"
  when: not ansible_check_mode

- name: Delete LDAP Pods before persistent data deletion
  ansible.builtin.include_role:
    name: dev_infra.deployment.k8s_deployment
    tasks_from: delete_labelled
  vars:
    dev_infra_deployment_delete_kind: Pod
    dev_infra_deployment_delete_namespace: "{{ dev_infra_deployment_namespace }}"
    dev_infra_deployment_delete_label_selectors:
      - "{{ dev_infra_deployment_ldap_pod_selector }}"
    dev_infra_deployment_delete_options:
      gracePeriodSeconds: 0
    dev_infra_deployment_delete_wait_sleep: "{{ dev_infra_deployment_pod_wait_sleep_seconds }}"

- name: Delete LDAP PVCs
  ansible.builtin.include_role:
    name: dev_infra.deployment.k8s_deployment
    tasks_from: delete_labelled
  vars:
    dev_infra_deployment_delete_kind: PersistentVolumeClaim
    dev_infra_deployment_delete_namespace: "{{ dev_infra_deployment_namespace }}"
    dev_infra_deployment_delete_label_selectors:
      - "{{ dev_infra_deployment_ldap_pod_selector }}"
