---
- name: Verify internal PKI ClusterIssuer
  kubernetes.core.k8s_info:
    kubeconfig: "{{ internal_pki_issuer_kubeconfig }}"
    api_version: cert-manager.io/v1
    kind: ClusterIssuer
    name: "{{ internal_pki_issuer_name }}"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_sleep: 5
    wait_timeout: "{{ internal_pki_issuer_wait_timeout_seconds }}"
  vars:
    ansible_python_interpreter: "{{ internal_pki_issuer_python_interpreter }}"
  changed_when: false
