#!/bin/sh
set -eu

awk '
$0 == "kind: CSIDriver" {
  csi_driver = 1
}

csi_driver && $0 == "metadata:" {
  print
  print "  labels:"
  print "    dev-infra.deployment/ownership: exclusive"
  csi_driver = 0
  next
}

{
  print
}
'
