---
dev_infra_deployment_python_interpreter: "{{ ansible_playbook_python }}"
dev_infra_deployment_helm_bin: helm
dev_infra_deployment_storage_class: nfs-csi
dev_infra_deployment_control_node_kubeconfig_path:
  "{{ (inventory_dir | dirname) ~ '/.ansible/runtime/kubeconfig' }}"
dev_infra_deployment_validate_kubeconfig: true
dev_infra_deployment_wait_timeout: 5m
dev_infra_deployment_wait_timeout_seconds: 300
dev_infra_deployment_long_wait_timeout: 10m
dev_infra_deployment_long_wait_timeout_seconds: 600
dev_infra_deployment_job_delete_timeout_seconds: 60
dev_infra_deployment_job_wait_sleep_seconds: 5
dev_infra_deployment_rollout_wait_sleep_seconds: 5
dev_infra_deployment_pod_wait_sleep_seconds: 5
dev_infra_deployment_rke2_images_dir: /var/lib/rancher/rke2/agent/images
dev_infra_deployment_crictl_bin: /var/lib/rancher/rke2/bin/crictl
dev_infra_deployment_crictl_config: /var/lib/rancher/rke2/agent/etc/crictl.yaml
dev_infra_deployment_image_refs: []
dev_infra_deployment_image_file_name: dev-infra-deployment.txt
