---
- name: Ensure dev-infra deployment artifact root exists
  ansible.builtin.file:
    path: "{{ dev_infra_deployment_artifacts_root }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  check_mode: false

- name: Remove stale staged Vault artifacts
  ansible.builtin.file:
    path: "{{ dev_infra_deployment_vault_artifacts_root }}"
    state: absent
  check_mode: false

- name: Stage Vault artifacts
  ansible.builtin.copy:
    src: k8s/
    dest: "{{ dev_infra_deployment_vault_artifacts_root }}/"
    owner: root
    group: root
    mode: preserve
  check_mode: false
