---
- name: Uninstall Kubernetes application workloads
  hosts: k8s_workload_mgr
  become: true
  gather_facts: false
  pre_tasks:
    - name: Prepare Kubernetes deployment prerequisites
      ansible.builtin.import_role:
        name: dev_infra.deployment.k8s_deployment
        tasks_from: prerequisites
      tags: [always]
  tasks:
    - name: Uninstall OpenSearch Dashboard
      ansible.builtin.import_role:
        name: dev_infra.deployment.opensearch_dashboard
        tasks_from: uninstall
      tags: [opensearch_dashboard, dashboard]

    - name: Uninstall OpenSearch
      ansible.builtin.import_role:
        name: dev_infra.deployment.opensearch
        tasks_from: uninstall
      tags: [opensearch]

    - name: Uninstall etcd
      ansible.builtin.import_role:
        name: dev_infra.deployment.etcd
        tasks_from: uninstall
      tags: [etcd]
